<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <UserSecretsId>661bb1cf-857e-4f4e-9d31-df561db8d894</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!-- ? For sending emails -->
    <!-- ? For serializing/deserialing JSON -->
    <PackageReference Include="MailKit" Version="4.8.0" />
    <!-- ? For access to the user secrets functionality -->
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.1" />
    <!-- ? For access to the Get extension casting function on configurations -->
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

</Project>
